In [ ]:
import numpy as np
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
print(arr)


[3 2 0 1 2]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.random.rand(4, 5)
print(arr)

[[0.81291354 0.32208275 0.91868527 0.43006116 0.8508092 ]
 [0.48328597 0.14609534 0.63524301 0.93179623 0.51577184]
 [0.8279877  0.56983121 0.5967719  0.73331929 0.84111448]
 [0.9931852  0.61506337 0.05134113 0.69747928 0.13078013]]


In [ ]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1])

[20 21 22 23 24]


In [ ]:
arr = ([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
print((arr[::-1]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Sum: {arr.sum()}, Average: {arr.mean()}")

Sum: 45, Average: 5.0


In [ ]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 != 0])

[1 3 5 7 9]
